import Head from "next/head";
import Post from "../../components/Post";
import { PrismaClient } from "@prisma/client";
import Carousel from "../../components/Carousel"

export default function SinglePost({post, similar}) {
  return (
    <div style={{padding:"1rem"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Post post={post}/>
      <Carousel breakpoints={{
            760: {
                perPage: 2,
            },
            560:{
              perPage:1
            }
      }} perPage={3} slides={similar}/>
    </div>
  );
}

export async function getServerSideProps(context) {
  const prisma = new PrismaClient();
  const {id} = context.query
  const post = await prisma.Post.findUnique({
    where: {
      id: id
    },
    //select: {}
  })
  const similar = await prisma.Post.findMany({
    where: {
      tags: {
        hasEvery: post.tags,
      },
      NOT: {
        id: post.id
      },
    },
    orderBy: {
      date: "desc"
    },
    take: 10
  })
  return {
    props: {post, similar},
  };
}
