import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Login.module.css";
import {
  signIn,
  getProviders,
  getCsrfToken,
  //getSession
} from "next-auth/react";
import { googleIcon, facebookIcon, redditIcon } from "../svg/socialIcons";
import { getToken } from "next-auth/jwt"

export default function Login({ providers, csrfToken }) {

  return (
    <div>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <div className={styles.iconWrapper}>
            {Object.values(providers).filter((provider) => provider.name !== "Credentials").map((provider) => (
              <div className={styles.iconContainer} key={provider.name}>
                <button
                  className={styles.iconButton}
                  onClick={() => signIn(provider.id)}
                >
                  <div className={styles.icon}>
                    {provider.name === "Google"
                      ? googleIcon
                      : provider.name === "Reddit"
                      ? redditIcon
                      : facebookIcon}
                  </div>
                  <div style={{ fontSize: "18px", fontWeight: "500" }}>
                    Sign in with {provider.name}
                  </div>
                </button>
              </div>
            ))}
          </div>
          <hr />
          <form method="post" action="/api/auth/callback/credentials">
            <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
            <div className={styles.part}>
              <div>Email</div>
              <input name="username" type="email" placeholder="email" />
            </div>
            <div className={styles.part}>
              <div>Password</div>
              <input name="password" type="password" placeholder="password" />
            </div>
            <button type="submit" className={styles.btn}>
              Login
            </button>
            <Link href="/preset">
              <div className={styles.register}>I don't remember my password</div>
            </Link>
            <Link href="/register">
              <div className={styles.register}>I don't have an account</div>
            </Link>
          </form>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const token = await getToken({req:context.req})
  if (token) {
    // redirect
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  const csrfToken = await getCsrfToken(context);
  const providers = await getProviders();
  return {
    props: { providers, csrfToken },
  };
}
