import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Preset.module.css";
import { useRef } from "react";

export default function Preset({  }) {
  const mailRef = useRef()

  const tryPreset = async (e) => {
    e.preventDefault()
    const body = {mail:mailRef.current.value}
    const res = await fetch("api/auth/preset", {
      method: 'POST',
      body: JSON.stringify(body),
      headers: { "Content-Type": "application/json" }
    })
    const data = await res.json()
    console.log("data", data)
    if ("error" in data) {
      let error = data.error
      console.log(error)
      if (data.error === "user already defined") {
        
      }
    }
  }

  return (
    <div>
      <Head>
        <title>Reset</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          <form onSubmit={(e) => tryPreset(e)}>
            <div className={styles.part}>
              <div>Email</div>
              <input ref={mailRef} name="username" type="email" placeholder="email" />
            </div>
            <button type="submit" className={styles.btn}>
              Send me link
            </button>
            <Link href="/register">
              <div className={styles.register}>I don't have an account</div>
            </Link>
          </form>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  
  return {
    props: {  },
  };
}
