import Head from "next/head";
import styles from "../styles/Verify.module.css";
import { PrismaClient } from "@prisma/client";
import { useEffect } from "react";
import { useRouter } from "next/router"

export default function Verify({ name }) {

  const router = useRouter()
  useEffect(() => {
    if (name) {
      setTimeout(() => {
        router.push("/login")
      }, 2000);
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Verify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <div className={styles.wrapper}>
          {name ?
            <div>Welcome {name}! You are being redirected to login page.</div>
            :
            <div>error</div>
          }
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const prisma = new PrismaClient();
  const token = context.query.token
  if (!token) {
    // redirect
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  const user = await prisma.User.findUnique({
    where: {
      token: token
    },
    select: {
      name: true,
      email: true,
      password: true,
      expire: true,
      verified: true,
    }
  });
  if (user && user.expire > Date.now()) {
    await prisma.User.update({
      where: {
        email: user.email,
      },
      data: {
        verified: true,
        token: "",
        expire: 0,
      },
    });
    return {
      props: { name:user.name },
    };
  }
  return {
    props: {  },
  };
}
